### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MikeyBeez** [dougallj/applecpu#1]
Please excuse me for asking questions here.  I hope I'm not being a pain.  I just read Erik Engheims interesting article on the Secret Apple M1 Coprocessor where you are mentioned.  I'm confused by Apple's documentation.  I'm wondering what machine learning on the CPU means?  Is that on Apple's Neural Engine?  And then, of course, Apple mentions two ML Accelerators which I think could be two cores in their AMX coprocessor?  If I'm at all correct about this, for reasons of flexibility in design, Apple has hidden the details of where the code runs.  I believe that unless one requests the GPU, training & inference occur, as Apple's neural controller determines, on either the two ML accelerators or the 16 cores of the ANE. Moreover, If my calculations are correct, the ANE has 2048 ALUs that are analogous to CUDA cores.  Does this seem right to you?  Additionally, do the two ML Accelerators each have 128 additional ALUs?  And finally, can the ANE access all of the M1's available integrated memory and swap?  Sorry for the long list of questions.  I appreciate any info you can give.  Thank you.

**Comment by dougallj** [comment]
No idea, sorry - I know almost nothing about ML, ANE, nor Apple's marketing language.

Everything I know about AMX on the M1 is here: https://gist.github.com/dougallj/7a75a3be1ec69ca550e7c36dc75e0d6f (and die-shot analysis and speculation about A15/M2 https://twitter.com/dougallj/status/1446097016166051848 )

AMX is a lot more tightly coupled with the CPUs than ANE, but the CPUs themselves can also do multiplications, which is what "machine learning on the CPU" would mean to me. Apple has a lot of different hardware now, with a lot of different numbers of AMX units and with different throughput per unit, so I can't really comment on any of those numbers out of context.

**Comment by MikeyBeez** [comment]
Thanks again.

**Comment by MikeyBeez** [comment]
Thank you very much for your kind reply.  Cheers.
